### ISSUE TITLE
OpenHAB integration not working after Home Assistant Core 2025.11.0 update

### ISSUE THREAD

**Issue by kovacsla** [bob-tm/ha-openhab#10]
Description:
After updating Home Assistant to Core 2025.11.0, the OpenHAB integration stopped working. It was functioning correctly before the update, but now it fails to connect or load entities.

Steps to Reproduce:

Update Home Assistant Core to version 2025.11.0.
Restart the system.
Check the OpenHAB integration.

Expected Behavior:
The OpenHAB integration should work normally, and all entities should be available.

Actual Behavior:
The integration does not start, and errors appear in the logs (e.g., connection refused or API call failed).

Environment:

Installation type: Home Assistant OS
Core: 2025.11.0
Supervisor: 2025.11.1
Operating System: 16.3
Frontend: 20251105.0
OpenHAB version: 0.6

Relevant Logs:
```
Napló: homeassistant.config_entries
Forrás: config_entries.py:761
Először fordult elő: 11:08:29 (3 előfordulás)
Utoljára naplózva: 11:45:39

Error setting up entry 10.10.10.21 for openhab
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openhab/__init__.py", line 59, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, coordinator.platforms)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2589, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1176, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1176, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1176, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  [Previous line repeated 5 more times]
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1164, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1089, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1263, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1295, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1027, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/openhab/media_player.py", line 4, in <module>
    from homeassistant.components.media_player.const import (
    ...<6 lines>...
    )
ImportError: cannot import name 'MEDIA_TYPE_MUSIC' from 'homeassistant.components.media_player.const' (/usr/src/homeassistant/homeassistant/components/media_player/const.py)
```

**Comment by kovacsla** [comment]
Description:
As predicted in Issue #5 from 2024-11-06, the OpenHAB integration is now broken after updating Home Assistant to 2025.11.0.
There are two major problems:

Media Player entities fail to load because SUPPORT_* constants were removed from HA core and replaced by MediaPlayerEntityFeature.
Unload error occurs when removing the integration:
Error unloading entry for openhab
KeyError: '01J20VX8C0A486QNXPGNT8558P'

This happens because async_unload_entry assumes the coordinator key always exists.


Steps to reproduce:

Update Home Assistant to 2025.11.0.
Enable Media Player entities in OpenHAB integration.
Restart HA → integration fails.
Remove integration → KeyError in logs.


Expected behavior:
Integration should load Media Player entities and unload cleanly without errors.

Actual behavior:

Media Player entities crash due to API changes.
Unload fails with KeyError.


Environment:

Home Assistant Core: 2025.11.0
OpenHAB version: 0.6
Installation type: (Docker, Supervisor, OS)


Fix provided:
I have patched two files to restore compatibility:
✅ media_player.py (updated for new HA API + fallback)

Uses MediaPlayerEntityFeature instead of deprecated constants.
Adds required properties (volume_level, is_volume_muted, source, source_list).
Includes fallback for older HA versions.

Full file: media_player.py:
```
"""
OpenHAB Media Player integration for Home Assistant
Compatible with Home Assistant 2025.11.0 and includes fallback for older versions.
"""

import logging
from homeassistant.components.media_player import MediaPlayerEntity

try:
    # New API (2025.11.0 and later)
    from homeassistant.components.media_player import MediaPlayerEntityFeature
    NEW_API = True
except ImportError:
    # Fallback for older versions
    from homeassistant.components.media_player.const import (
        SUPPORT_PLAY,
        SUPPORT_PAUSE,
        SUPPORT_PREVIOUS_TRACK,
        SUPPORT_NEXT_TRACK,
        SUPPORT_VOLUME_SET,
    )
    NEW_API = False

_LOGGER = logging.getLogger(__name__)

DOMAIN = "openhab"

if NEW_API:
    SUPPORT_OPENHAB = (
        MediaPlayerEntityFeature.PLAY
        | MediaPlayerEntityFeature.PAUSE
        | MediaPlayerEntityFeature.PREVIOUS_TRACK
        | MediaPlayerEntityFeature.NEXT_TRACK
        | MediaPlayerEntityFeature.VOLUME_SET
    )
else:
    SUPPORT_OPENHAB = (
        SUPPORT_PLAY
        | SUPPORT_PAUSE
        | SUPPORT_PREVIOUS_TRACK
        | SUPPORT_NEXT_TRACK
        | SUPPORT_VOLUME_SET
    )


async def async_setup_entry(hass, config_entry, async_add_entities):
    """Set up OpenHAB Media Player entities from a config entry."""
    coordinator = hass.data[DOMAIN][config_entry.entry_id]
    players = [item for item in coordinator.data.values() if item.type_ == "Player"]
    entities = [OpenHABMediaPlayer(item, coordinator) for item in players]
    async_add_entities(entities)


class OpenHABMediaPlayer(MediaPlayerEntity):
    """Representation of an OpenHAB Media Player entity."""

    def __init__(self, item, coordinator):
        self._item = item
        self._coordinator = coordinator
        self._attr_name = item.label or item.name
        self._attr_unique_id = f"openhab_{item.name}"
        self._state = None
        self._volume_level = None
        self._is_muted = False
        self._source = None
        self._source_list = []

    @property
    def supported_features(self):
        return SUPPORT_OPENHAB

    @property
    def state(self):
        return self._state or "off"

    @property
    def volume_level(self):
        # Return a dummy value or actual value if available
        return self._volume_level if self._volume_level is not None else 0.5

    @property
    def is_volume_muted(self):
        return self._is_muted

    @property
    def source(self):
        return self._source

    @property
    def source_list(self):
        return self._source_list

    async def async_media_play(self):
        await self._send_command("PLAY")

    async def async_media_pause(self):
        await self._send_command("PAUSE")

    async def async_media_next_track(self):
        await self._send_command("NEXT")

    async def async_media_previous_track(self):
        await self._send_command("PREVIOUS")

    async def async_set_volume_level(self, volume):
        self._volume_level = volume
        await self._send_command(f"VOLUME {int(volume * 100)}")

    async def _send_command(self, command):
        try:
            await self._coordinator.send_command(self._item.name, command)
            _LOGGER.debug("Sent command %s to %s", command, self._item.name)
        except Exception as e:
            _LOGGER.error("Failed to send command %s to %s: %s", command, self._item.name, e)
```


✅ __init__.py (safe unload logic)
```
"""
Custom integration to integrate openHAB with Home Assistant.

For more details about this integration, please refer to
https://github.com/kubawolanin/ha-openhab
"""
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant

from .api import OpenHABApiClient
from .const import (
    CONF_AUTH_TOKEN,
    CONF_AUTH_TYPE,
    CONF_BASE_URL,
    CONF_PASSWORD,
    CONF_USERNAME,
    DOMAIN,
    LOGGER,
    PLATFORMS,
    STARTUP_MESSAGE,
)
from .coordinator import OpenHABDataUpdateCoordinator


async def async_setup_entry(
    hass: HomeAssistant,
    entry: ConfigEntry,
) -> bool:
    """Set up this integration using UI."""
    LOGGER.info(STARTUP_MESSAGE)
    hass.data.setdefault(DOMAIN, {})

    api_client = OpenHABApiClient(
        hass=hass,
        base_url=entry.data[CONF_BASE_URL],
        auth_type=entry.data[CONF_AUTH_TYPE],
        auth_token=entry.data.get(CONF_AUTH_TOKEN, ""),
        username=entry.data.get(CONF_USERNAME, ""),
        password=entry.data.get(CONF_PASSWORD, ""),
    )

    if api_client.openhab==False:
        LOGGER.info("OpenHab Recreating Oauth2 Token")
        api_client._creating_token = True
        await api_client.async_get_auth2_token()
        api_client.CreateOpenHab()

    coordinator = OpenHABDataUpdateCoordinator(hass, api=api_client)
    await coordinator.async_config_entry_first_refresh()

    hass.data[DOMAIN][entry.entry_id] = coordinator

    for platform in PLATFORMS:
        if entry.options.get(platform, True):
            coordinator.platforms.append(platform)
            #hass.async_add_job(
            #    hass.config_entries.async_forward_entry_setup(entry, platform)
            #)
    await hass.config_entries.async_forward_entry_setups(entry, coordinator.platforms)

    entry.add_update_listener(async_reload_entry)

    return True



async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Unload the config entry."""
    coordinator = hass.data.get(DOMAIN, {}).get(entry.entry_id)
    if not coordinator:
        # Kulcs nem található, nincs mit unloadolni
        return True

    unload_ok = await hass.config_entries.async_unload_platforms(
        entry, [platform for platform in PLATFORMS if platform in coordinator.platforms]
    )

    if unload_ok:
        hass.data[DOMAIN].pop(entry.entry_id, None)

    return unload_ok


async def async_reload_entry(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Reload config entry."""
    await async_unload_entry(hass, entry)
    await async_setup_entry(hass, entry)

```


Suggested action:
Please merge these fixes or update the integration to support HA 2025.11.0.

**Comment by MrDix** [comment]
This issue is already fixed in PR #9!

The error you're experiencing is caused by deprecated constants that were removed in Home Assistant 2025.10+. This has been fixed in commit eada16ddf06e96253355e88e3fbd33282fff3478.

**Solution:**
The fix updates the deprecated imports:
- `MEDIA_TYPE_MUSIC` → `MediaType.MUSIC`
- `SUPPORT_*` constants → `MediaPlayerEntityFeature.*`
- `COLOR_MODE_*` constants → `ColorMode.*`

---

## Option 1: Wait for PR #9 to be merged (Recommended - easiest)

Simply wait for the PR to be merged, then:
1. Update the integration through HACS
2. Restart Home Assistant

---

## Option 2: Switch to my fork for immediate fix (Advanced)

**⚠️ Warning:** This requires editing HACS configuration files. Your entity IDs and configuration will be preserved.

1. **Stop Home Assistant**
2. **Backup the HACS configuration file:**
   Navigate to `/config/.storage/hacs.repositories` duplicate the file with a different name as a backup in case something goes wrong while implementing the next step.
2. **Edit the HACS configuration file:**
   Navigate to `/config/.storage/hacs.repositories` and find the openHAB entry
3. **Change the repository URL:**
   Replace `bob-tm/ha-openhab` with `MrDix/ha-openhab`
   ```json
   "full_name": "MrDix/ha-openhab"
   ```
4. **Restart Home Assistant**
5. **In HACS:**
   - Go to the openHAB integration
   - Click the three dots menu → "Redownload"
   - This will download from my fork with all fixes included

6. **Restart Home Assistant again**

Your entity IDs and configuration will remain intact.

---

## Option 3: Manual file replacement

If you're comfortable with file operations:

1. Download the fixed files from my fork:
   - [[media_player.py](https://raw.githubusercontent.com/MrDix/ha-openhab/master/custom_components/openhab/media_player.py)](https://raw.githubusercontent.com/MrDix/ha-openhab/master/custom_components/openhab/media_player.py)
   - [[light.py](https://raw.githubusercontent.com/MrDix/ha-openhab/master/custom_components/openhab/light.py)](https://raw.githubusercontent.com/MrDix/ha-openhab/master/custom_components/openhab/light.py)

2. Replace the existing files in `/config/custom_components/openhab/`

3. Restart Home Assistant

---

See PR #9 for full details of all improvements including this fix.

**Comment by kovacsla** [comment]
I’ve fixed issues #4 and #5 as well. If you’d like, I can send you the modified files.

**Comment by kovacsla** [comment]
[mod_files.zip](https://github.com/user-attachments/files/23518902/mod_files.zip)

**Comment by MrDix** [comment]
This is the same root cause as issue #5 - the deprecated `MEDIA_TYPE_MUSIC` and `SUPPORT_*` constants from `media_player.const` were removed in HA 2025.10/2025.11. This is fixed in PR #9 (from the MrDix fork), which updates all affected imports to the current enum-based equivalents.

Until PR #9 is merged, you can switch to the fork as a workaround:

```
https://github.com/MrDix/ha-openhab
```

Copy `custom_components/openhab/` into your HA config directory, or add the repository in HACS as a custom integration source.
